name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: echo 'No tests yet'

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ethionav-backend
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
